### ISSUE TITLE
Error on starting the server

### ISSUE THREAD

**Issue by gopidon** [MattMcFarland/reactathon#14]
Hi,

I following the exact steps mentioned in README but I get the following error. The browser then opens pointing to localhost:3000 but it times out after sometime

> reactathon@0.0.1 copy:static /Users/gopi/relayjs/reactathon
> cp -R server/src/public lib/public && cp -R server/src/pages lib/pages && cp server/src/.env.example lib

module.js:340
    throw err;
    ^

Error: Cannot find module '/Users/gopi/relayjs/reactathon/lib/bin/server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by MattMcFarland** [comment]
@gopidon 

Well, this is embarrassing!

Apparently the bin folder was in `.gitignore`, so theoretically I can't see how anyone could have used it.  I think I should have caught this, but for some reason my IDE didn't show the bin folder as being affected.

Sorry for the trouble this caused you.  I have pushed changes that fix the issue.

If you haven't removed your directory yet, you can run the following command to update the server, rebuild, and run.

```
git fetch && git pull && npm run dev
```

if you deleted your workspace, please follow the same steps in README.

Let me know if this works!

Thanks

**Comment by MattMcFarland** [comment]
@gopidon Can you confirm these changes?  I'll be closing this in a couple days if no response.

**Comment by gopidon** [comment]
Hi Matt,

Looks good. I do get some other error but I guess thats coz I haven't set
the keys in config file. Thank you.

**Comment by MattMcFarland** [comment]
@gopidon You shouldn't get another error, can you elaborate?

**Comment by gopidon** [comment]
I dont get it anymore. Did see it yesterday. It was complaining that one of the URLs in the config file was missing (STEAMBACK_URL ?). Probably, some of the recent code pushes fixed it.

Currently, the browser launches and the UI shows up. However, it's taking a lot of time for the UI to show up for the very first time. Any thoughts there?

**Comment by MattMcFarland** [comment]
@gopidon I experience the slow start as well, I think this has something to do with browsersync, but I'm not sure.  Once the server is started though, it runs very fast and when you make changes it quickly updates them so you don't have to restart the server manually. 

It's worthy of investigation, I'll probably take a look and try to fix that issue later.  You can also speed things up by clicking the X and hitting refresh. again, this is only when it first starts up, as you develop and make changes it runs refreshes quickly.

**Comment by MattMcFarland** [comment]
Closing the issue, will make another issue for the slow start.

**Comment by MattMcFarland** [comment]
@gopidon I have sped it up!  You can also go even faster if you use `npm run watch` instead of `npm run dev` - because `npm run dev` runs build scripts.  If you already built, then `npm run watch` is fine.
