### ISSUE TITLE
Unexpected token: babel-relay-plugin-loader: using schema at .../data/schema.json

### ISSUE THREAD

**Issue by richb-hanover** [MattMcFarland/reactathon#31]
Using reactathon (fresh clone of 7beea6e) on OSX 10.10.5 running Node 5.3.0, npm 3.3.12. I ran `npm install && npm run dev` The npm install ran fine, but I get an error trying to start up the app. 

Although I have installed/removed some npm packages, I can't think of differences between what I was trying to do the other day (when things worked...)

NB: the file /Users/richb/github/reactathon/npm-debug.log does not exist.

What other information could I provide?

```
...
> reactathon@0.0.1 copy:static /Users/richb/github/reactathon
> cp -R server/src/public lib/public && cp -R server/src/pages lib/pages && cp server/src/.env.example lib

[stdin]:1
babel-relay-plugin-loader: using schema at [/Users/richb/github/reactathon/data/schema.json]
                         ^

SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:398:26)
    at node.js:592:27
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 dev: `npm run build && babel scripts/server.js | node`
npm ERR! Exit status 1
```

Full text at: http://pastebin.com/ww0xgKrK

**Comment by MattMcFarland** [comment]
It looks like something is wrong with update-schema, can you try `npm run update-schema` - that should give you an error but maybe a more descriptive one.

Another thing you can try is also verifying that the schema directory exists

**Comment by richb-hanover** [comment]
Regrettably, no. After `npm run update-schema` completes, `npm run dev` returns the same error message. 

```
bash-3.2$ npm run update-schema

> reactathon@0.0.1 update-schema /Users/richb/github/reactathon
> babel-node ./scripts/updateSchema.js

babel-relay-plugin-loader: using schema at [/Users/richb/github/reactathon/data/schema.json]
bash-3.2$
```

**Comment by MattMcFarland** [comment]
i will investigate this tonight, but I think it might have something to do with a version discrepancy with `babel-relay-plugin-loader`  maybe try `npm install babel-relay-plugin-loader@0.6.1` ??

**Comment by richb-hanover** [comment]
Ahah. It's working! Here's what I did:

```
npm install --save-dev babel-relay-plugin@0.6.3
npm install --save-dev babel-relay-plugin-loader@0.6.1
npm uninstall -g babel-relay-plugin
npm uninstall -g babel-relay-plugin-loader
```

then remove babel-relay-plugin and babel-relay-plugin-loader from the dependencies section of package.json (the first two commands above will put them in devDependencies section)

I note that many of the packages used during building the project (babel*, mocha, others?) could get the same treatment so that the project isn't subject to the vagaries of the versions people have installed. (I also think that they won't be included in the built files, since they're marked as devDependencies.)

I also fixed a problem with WebStorm giving a ton of messages like this: "The CLI has been moved into the package 'babel-cli'" The fix is updating watchers as described in http://blog.jetbrains.com/webstorm/2015/05/ecmascript-6-in-webstorm-transpiling/

Thanks.

**Comment by MattMcFarland** [comment]
Well done!  So moving it into devDependencies and setting a specific version did the trick?

**Comment by richb-hanover** [comment]
Yes. Those commands did the trick. As I said above, I suspect it would be valuable to do the same (removing global packages and adding local versions) for all the build tools (babel_, mocha?, chai?, eslint?, gulp_?, others?) even if it only saves space for the distributable files...

And I wonder if getting the latest of the build tools might be the best strategy... (Sorry, I'm no expert here...)

**Comment by MattMcFarland** [comment]
Yes, getting the latest is a good idea, I think we can use something like greens-keeper.  Moving those to devDependencies will be good.

**Comment by MattMcFarland** [comment]
Updated devDependencies
