### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by bookercodes** [MattMcFarland/reactathon#33]
After running `npm install` and then `npm run dev`, I get the following error:

```
> reactathon@0.0.1 copy:static /home/booker/Code/reactathon
> cp -R server/src/public lib/public && cp -R server/src/pages lib/pages && cp server/src/.env.example lib

[stdin]:1
babel-relay-plugin-loader: using schema at [/home/booker/Code/reactathon/data/schema.json]
                         ^

SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:612:27
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/home/booker/.nvm/versions/node/v5.6.0/bin/node" "/home/booker/.nvm/versions/node/v5.6.0/bin/npm" "run" "dev"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 dev: `npm run build && babel scripts/server.js | node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactathon@0.0.1 dev script 'npm run build && babel scripts/server.js | node'.> reactathon@0.0.1 copy:static /home/booker/Code/reactathon
> cp -R server/src/public lib/public && cp -R server/src/pages lib/pages && cp server/src/.env.example lib

[stdin]:1
babel-relay-plugin-loader: using schema at [/home/booker/Code/reactathon/data/schema.json]
                         ^

SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:612:27
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/home/booker/.nvm/versions/node/v5.6.0/bin/node" "/home/booker/.nvm/versions/node/v5.6.0/bin/npm" "run" "dev"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! reactathon@0.0.1 dev: `npm run build && babel scripts/server.js | node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactathon@0.0.1 dev script 'npm run build && babel scripts/server.js | node'.
```

**Comment by abinashk** [comment]
I also got the same error. The problem is caused by 3 lines of console.log() codes in /node_modules/babel-relay-plugin-loader/index.js :

console.log('babel-relay-plugin-loader: using schema at [' + schemaPath + ']');
console.log('babel-relay-plugin-loader: no schema found at [' + schemaPath + ']');
console.log('babel-relay-plugin-loader: babel will continue without the babel-relay-plugin!');

This error disappeared when I commented out these three lines. Although this is not the right way to do it since the bug is coming from a downloaded package and you'll need to apply this fix every time you deploy the app, if you are in a pressing need for a working installation then it can help.

**Comment by MattMcFarland** [comment]
I wonder if we should use a specific version?  Maybe set back a version or
two and make it permanent in package.json?

On Wed, Feb 17, 2016 at 11:01 AM, Abinash Koirala notifications@github.com
wrote:

> I also got the same error. The problem is caused by 3 lines of
> console.log() codes in /node_modules/babel-relay-plugin-loader/index.js :
> 
> console.log('babel-relay-plugin-loader: using schema at [' + schemaPath +
> ']');
> console.log('babel-relay-plugin-loader: no schema found at [' + schemaPath
> - ']');
>   console.log('babel-relay-plugin-loader: babel will continue without the
>   babel-relay-plugin!');
> 
> This error disappeared when I commented out these three lines. Although
> this is not the right way to do it since the bug is coming from a
> downloaded package and you'll need to apply this fix every time you deploy
> the app, if you are in a pressing need for a working installation then it
> can help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/reactathon/issues/33#issuecomment-185271507
> .

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by robbyoconnor** [comment]
I made a PR which fixes the issue https://github.com/BerndWessels/babel-relay-plugin-loader/pull/7

**Comment by robbyoconnor** [comment]
Temproary fix: 
`npm install git://github.com/robbyoconnor/babel-relay-plugin-loader#use-template-strings --save-dev`

**Comment by MattMcFarland** [comment]
Awesome thanks!

On Sun, Feb 21, 2016 at 12:25 AM, robbyoconnor notifications@github.com
wrote:

> Temproary fix:
> 
> npm install git://github.com/robbyoconnor/babel-relay-plugin-loader#use-template-strings --save-dev
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MattMcFarland/reactathon/issues/33#issuecomment-186748694
> .

## 

Matt McFarland

Software Engineer | @docodemore https://twitter.com/docodemore | LinkedIn
http://www.linkedin.com/pub/matthew-mcfarland/6a/b9a/135/en | Mobile:
513.638.8685 | Office: 937.865.6800 xt: 125010

**Comment by robbyoconnor** [comment]
Update: My PR was accepted -- and tested it -- works like a charm!

**Comment by bookercodes** [comment]
Thanks, @robbyoconnor !!
